### ISSUE TITLE
建议增加支持SMBus协议

### ISSUE THREAD

**Issue by rinscr3003** [rcdrones/UPSPACK_V2#2]
看到板子上有新唐的单片机，觉得这个东西应该也能做SMBus协议的电池监控。
而且这样的话在系统中就可以原生识别电池信息，比自己开发在集成度上会更有优势。
另外，串口就一个，占了的话再接热敏打印机什么的很头疼。SMBus和I2C是兼容的，而I2C总线上可以挂载多个设备，不会影响其他外设链接。

**Comment by rcdrones** [comment]
1. 我们开发了 one wire warning 从而不用占用串口。 此外pi4 串口有 4对。 也不再是独占关系。
smbus没有研究过，后期版本升级可能会考虑进去。最近在做b站 的更新，心有余而力不足 ：）
